### ISSUE TITLE
Una mini-guía de estilo ayudaría a evitar conflictos, y facilitiaría la contribución

### ISSUE THREAD

**Issue by JJ** [JJ/pelooxtreem#17]
Por ejemplo en #14 se ha propuesto nombres de ficheros usando `CamelCase`. Usar convenciones estándar ayuda a dar un aspecto uniforme y más profesional al proyecto, y favorece la adopción de buenas prácticas, y de buenas prácticas uniformes, en el proyecto.

**Comment by fjgallardo00** [comment]
Para seguir convecciones estándares entre todos, se va a crear un archivo contributing.md donde se indique cómo tener buenas prácticas uniformes para todos.
