### ISSUE TITLE
¿Cuándo un día va a estar completo? 

### ISSUE THREAD

**Issue by JoseCarlosPPK** [JJ/pelooxtreem#4]
Necesitamos saber con cuántos clientes decidimos si un día está completo o no según dice la HU #1 . ¿Con 10 clientes está el día ocupado? ¿Depende de lo que se tarda en el servicio ofrecido? ¿Está información se recoge en los informes #3 ?

**Comment by pablo1mc315** [comment]
Primero que nada, necesitamos saber el horario de la peluquería y el número de clientes que se puede atender a la vez en la peluquería (si tenemos 3 puestos en nuestro local, no podemos citar a 4 clientes a la misma hora).

**Comment by JoseCarlosPPK** [comment]
Se podría asumir que un peluquero solo puede estar con un cliente a la vez. Es decir, tener una relación 1:1

**Comment by pablo1mc315** [comment]
Vamos a considerar que se irán asignando clientes a un mismo trabajador hasta llenar su turno. Una vez completado un turno, si se siguen pidiendo citas para ese mismo día, necesitamos otro trabajador. Esto se repetirá tantas veces como puestos tengamos en el local.

**Comment by martahuetem** [comment]
Necesitamos saber qué tiene pensado hacerse el cliente para saber su tiempo y saber cuantos clientes podemos tener ese día. Para ello modelizaremos el objeto valor **cita**.

**Comment by JoseCarlosPPK** [comment]
Queremos saber cuándo un día está completo: por tanto creo que da igual si los clientes son inesperados o ya estaban previstos con las citas. Un cliente inesperado que quiera realizarse el servicio **x** , ¿se tarda más que un cliente con cita con el mismo servicio? Pienso que no

**Comment by mariavallejo20** [comment]
Vamos a predecir el pico de clientes teniendo en cuenta dos factores:
* Las citas reservadas en un día.
* Basándonos en los informes, predecir el número de clientes que pueden asistir sin cita.

**Comment by pablo1mc315** [comment]
Debemos implementar una estructura de datos que contenga:

- La información relacionada a cada cita (objeto valor).
- La información relacionada a cada trabajador que atenderá una cita (objeto valor).
- La información relacionada a cada turno que contenderá una serie de citas y el trabajador que las atiende (objeto valor).

**Comment by mariavallejo20** [comment]
> Debemos implementar una estructura de datos que contenga:
> 
> * La información relacionada a cada cita (objeto valor).
> * La información relacionada a cada trabajador que atenderá una cita (objeto valor).
> * La información relacionada a cada turno que contenderá una serie de citas y el trabajador que las atiende (objeto valor).

La modelización de cada trabajador no será necesaria ya que está incluida en #5
