### ISSUE TITLE
Modelizar los trabajadores que necesito

### ISSUE THREAD

**Issue by MauronMP** [JJ/pelooxtreem#5]
Para la #1 y la gestión de #4

**Comment by MarinoFajardo** [comment]
Para la representación del modelo de los trabajadores, es necesario conocer las funciones que puede realizar cada trabajador.

**Comment by fjgallardo00** [comment]
Hay que saber qué tipos de servicios ofrece la peluquería para saber las funciones que puede realizar un trabajador

**Comment by RafaelT00** [comment]
Hay que tomar en cuenta también las horas que esté dispuesto a echar cada trabajador y cuánto cobraría por las horas

**Comment by MarinoFajardo** [comment]
> Hay que tomar en cuenta también las horas que esté dispuesto a echar cada trabajador y cuánto cobraría por las horas

Con respecto a esto vamos a suponer que el sueldo del trabajador no es relevante para la lógica de negocio al igual que las horas de trabajo, ya que hay unos horarios de trabajo establecidos por convenio.

**Comment by martahuetem** [comment]
Hola @MauronMP @MarinoFajardo @JJ @fjgallardo00 @RafaelT00. 
Creemos necesario identificar al trabajador de alguna manera. Ya sea con ID o DNI o algo así.

**Comment by MauronMP** [comment]
> Hola @MauronMP @MarinoFajardo @JJ @fjgallardo00 @RafaelT00. Creemos necesario identificar al trabajador de alguna manera. Ya sea con ID o DNI o algo así.

Eso estábamos pensando en nuestro grupo, nosotros estamos con la clase servicio y trabajador, en principio le asignaremos un ID al trabajador a menos que alguien prefiera otra cosa.

**Comment by JJ** [comment]
¿Nombre y apellidos no son suficientes?
En realidad no lo vas a buscar por nombre, sino por los servicios que ofrece. Si hay dos con el mismo nombre y apellidos y ofrecen los mismos servicios, tenemos un problema. Pero si no...

**Comment by JJ** [comment]
> Hay que tomar en cuenta también las horas que esté dispuesto a echar cada trabajador y cuánto cobraría por las horas

Rafael, mientras que las horas sí entran en consideración en este milestone, cuanto va a cobrar no forma parte de la historia de usuario, que sólo habla de contratar trabajadores.

Cuantas horas estaría dispuesto a trabajar, vamos a suponer que está disponible a tiempo completo. Cualquier otra cosa adicional necesitaría otra historia de usuario. Te animo a crear esa historia de usuario si crees que es importante.
