### ISSUE TITLE
Modelización del tiempo de cada servicio.

### ISSUE THREAD

**Issue by mariavallejo20** [JJ/pelooxtreem#6]
Debemos tener en cuenta el tiempo que se tarda en realizar cada servicio determinado, para saber cuando un día estará completo #4.

**Comment by delightfulagony** [comment]
Deberíamos definir qué servicios ofrece la peluquería

**Comment by luistf24** [comment]
También tenemos que saber el tiempo medio que se trabaja en cada servicio

**Comment by fjromeero** [comment]
También deberíamos saber el tiempo útil que se trabaja en este servicio (siendo tiempo util, el tiempo en el que esta trabajando directamente con el cliente)

**Comment by luistf24** [comment]
Necesitamos identificar un servicio de manera que no se presenten confusiones entre otros

**Comment by delightfulagony** [comment]
> Necesitamos identificar un servicio de manera que no se presenten confusiones entre otros

Asignamos un nombre al servicio que sirva como identificador

**Comment by delightfulagony** [comment]
:parrot:

**Comment by MauronMP** [comment]
🤮

**Comment by fjromeero** [comment]
?
